spring.application.name=pos-customer
server.port=8084
server.servlet.context-path=/api/customer

spring.datasource.url=jdbc:postgresql://localhost:5432/pos_customer
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

jwt.secret=mySuperSecretKeyForJwtTokenGeneration123456

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.preferIpAddress=true
