spring.application.name=pos-reporting
server.port=8085
server.servlet.context-path=/api/reports

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.preferIpAddress=true
